base_url = "https://kashishkapoor.com"
title = "Kashish"
description = "Personal blog"
theme = "apollo"

# Syntax highlighting and search
build_search_index = true
generate_feeds = true         # Creates RSS feed (corrected from generate_feed)
compile_sass = true          # Enables Sass/SCSS compilation


[markdown]
highlight_code = true
highlight_theme = "dracula"    # Code highlighting theme
render_emoji = true           # Enables emoji rendering
external_links_target_blank = true    # Opens external links in new tab
external_links_no_follow = true       # Adds nofollow to external links
smart_punctuation = true             # Enables smart punctuation

[extra]
# Theme configuration
theme = "toggle"              # Options: "light", "dark", "auto", "toggle"
use_cdn = false              # Set to true if you want to use CDN for assets
toc = false                   # Enable table of contents
favicon = "/favicon.svg" # Path to your favicon
fancy_code = true            # Enables fancy code block styling
dynamic_note = true          # Enables dynamic notes feature

# Navigation menu
menu = [
    { name = "/writings", url = "/writings", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
    { name = "/financial planning", url = "/financial-planning", weight = 3 },
    { name = "/financeradar", url = "/finance-radar", weight = 4 },
]

# Social media links
socials = [
    # Add your social media links here, for example:
    { name = "twitter", url = "https://x.com/kashishkap00r", icon = "twitter" },
    { name = "linkedin", url = "https://www.linkedin.com/in/kashishkap00r", icon = "linkedin" },
    { name = "email", url = "mailto:kashishkapoor538@gmail.com", icon = "email" }, 
    { name = "youtube", url = "https://www.youtube.com/@kashishkap00rYT", icon = "youtube" },
    ]
    

# Optional: Analytics configuration
[extra.analytics]
enabled = false
